export ROKI_MB_SERIAL_BAUDRATE=1250000
export ROKI_MB_SERIAL_STOPBITS=1
export ROKI_MB_SERIAL_PARITY=1
export ROKI_MB_SERIAL_TIMEOUT=1

export ROKI_MB_DAEMON_PORT=8079
export ROKI_MB_DAEMON_BACKLOG=5
export ROKI_MB_DAEMON_LOGFILE=/tmp/roki-mb-daemon-logs.txt
